### ISSUE TITLE
py_get_attr_impl(x, name, silent) :    AttributeError: 'AxisArrays' object has no attribute 'X_dca'

### ISSUE THREAD

**Issue by MaxKman** [jingshuw/SAVERX#2]
Hi,

thanks for developing SAVERX - great idea. I tried to run it on MacOS Mohave 10.14.3 with R 3.5.2 using your test dataset and the suggested command from the manual but it fails with an error. Here is the output:

> saverx("./testdata/shekhar_downsampled.csv")
> [1] "Input file is: ./testdata/shekhar_downsampled.csv"
> [1] "Use a pretrained model: No"
> Using TensorFlow backend.
> 
> [1] "Python module sctransfer imported ..."
> [1] "Processed file saved as: ./testdata/shekhar_downsampled_temp.rds"
> [1] "Data preprocessed ..."
> [1] "Cross-validation round: 1"
> 
> Error in py_get_attr_impl(x, name, silent) : 
>   AttributeError: 'AxisArrays' object has no attribute 'X_dca'
> Timing stopped at: 208.4 15.33 28.45

help appreciated.

Best
Max

**EDIT:** the test sample runs through fine when setting `is.large.data = T`. I don't think it's a memory issue though, since I have plenty of RAM to spare while running.

**Comment by jingshuw** [comment]
Thanks for letting me know. Will debug the issue as soon as possible.

**Comment by jingshuw** [comment]
Does that error come up when you run SAVER-X the second time? Currently, due to an issue of removing Python object from R, if you run SAVER-X the second time, you should open a new R session. I do not see why the error comes out. We now take a different file storing and generating approach and your error may go away. I would appreciate it a lot if you can install the newer version of SAVER-X and give it a try another time.

**Comment by jingshuw** [comment]
The error is solved by updating the reticulate R package to version 1.13. Older versions seem to be incomparable with tensorflow 2.0
