### ISSUE TITLE
Recommended workflow for multiple samples

### ISSUE THREAD

**Issue by MaxKman** [jingshuw/SAVERX#3]
Hi again,

I wonder what your recommendations are for using SAVERX with multiple samples. In my work I integrate > 20 samples using Seurat V3 to identify overarching cell clusters. If I want to use SAVERX on these samples, would you recommend to

a) integrate the data and run SAVERX on the integrated data (probably not, since UMI count data is lost on the way)
b) run SAVERX on one big matrix with UMI counts from all cells of all samples
c) run SAVERX on the UMI counts of each sample separately and integrate the resulting data using Seurat?

Or is there another way altogether?

Thanks for your help and thanks again for developing this!

Best Max

**Comment by jingshuw** [comment]
Hi Max,

My opinion is that either b or c would work. If you use b and your matrix is too big, then remember to set is.large.data = T. Since SAVERX currently does not remove batch effect, you still need to integrate resulting data using Seurat. If you choose option c, then if the numbers of cells in some samples is too small (hundreds of cells), then it would perform as good as option b. If each sample has thousands of cells, then b/c would not be too different.

**Comment by MaxKman** [comment]
Hi Jingshuw,

thanks for the quick response. Are you saying that separating the samples is better or worse when some samples have only hundreds of cells?

Best Max

**Comment by jingshuw** [comment]
If you are dealing with immune cells where we have a good pre-trained model available, SAVER-X performs well only on a few hundred cells. Whether merge different batches together to denoise is currently a rule of thumb in SAVER-X. If you want to compare across samples, then I would suggest merge all samples together and denoise.
